name: Get Secrets

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Please select the environment you wish to deploy to'
        required: true
        options:
              - Environment1
              - Environment2
        
jobs:
    test-relogin:
      environment: ${{ inputs.env_name }}
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: write
        pull-requests: write
        actions: write
        
      steps:

      - name: Login via Az module
        uses: azure/login@v1
        with:
         creds: ${{secrets.AZURE_CREDENTIALS}}
         enable-AzPSSession: true 

      - name: Find RG try 1
        shell: bash
        run: |
         $details = Get-AzResourceGroup -SubscriptionId "f40ff74c-f3fb-4c44-9baa-506db6aacb38"
         echo $details

      - name: Find RG try 2
        uses: azure/CLI@v1
        with:
         azcliversion: 2.30.0
         inlineScript: |
          $details = Get-AzResourceGroup -SubscriptionId "f40ff74c-f3fb-4c44-9baa-506db6aacb38"
          echo $details
         
      - name: Print vars
        shell: bash
        run: |
          echo ${{ secrets.SECRET_NAME }} | sed 's/./& /g'
          echo ${{ vars.name }} | sed 's/./& /g'
          
