name: Get Secrets

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: 'Please select the environment you wish to deploy to'
        required: true
        options:
              - Environment1
              - Environment2
        
jobs:
    test-relogin:
      environment: ${{ inputs.env_name }}
      runs-on: ubuntu-latest
      permissions:
        id-token: write
        contents: write
        pull-requests: write
        actions: write
        
      steps:
        
      - name: Login via Az module
        uses: azure/login@v1
        with:
         creds: ${{secrets.AZURE_CREDENTIALS}}
         enable-AzPSSession: true 

      - name: Login via Az module
        uses: azure/login@v1
        with:
         creds: ${{secrets.AZURE_CREDENTIALS1}}
         enable-AzPSSession: true 


      - name: Get RG with powershell action
        uses: azure/powershell@v1
        with:
          inlineScript: |
             Get-AzResourceGroup
             azPSVersion: "latest"

        
      - name: Print vars
        shell: bash
        run: |
          echo ${{ secrets.SECRET_NAME }} | sed 's/./& /g'
          echo ${{ vars.name }} | sed 's/./& /g'
          
